Add vpn

diff --git a/cwa-downloader/templates/deployment.yaml b/cwa-downloader/templates/deployment.yaml
--- a/cwa-downloader/templates/deployment.yaml
+++ b/cwa-downloader/templates/deployment.yaml
@@ -16,6 +16,45 @@ spec:
       nodeSelector:
         {{- toYaml . | nindent 8 }}
       {{- end }}
+      initContainers:
+      - name: vpn
+        image: {{ .Values.vpn.image }}:{{ .Values.vpn.imageTag }}
+        restartPolicy: Always
+        securityContext:
+          capabilities:
+            add:
+            - NET_ADMIN
+        env:
+        - name: VPN_SERVICE_PROVIDER
+          value: nordvpn
+        - name: VPN_TYPE
+          value: openvpn
+        - name: OPENVPN_USER
+          valueFrom:
+            secretKeyRef:
+              name: slskd
+              key: OPENVPN_USER
+        - name: OPENVPN_PASSWORD
+          valueFrom:
+            secretKeyRef:
+              name: slskd
+              key: OPENVPN_PASSWORD
+        - name: DNS_KEEP_NAMESERVER
+          value: "on"
+        - name: FIREWALL_OUTBOUND_SUBNETS
+          value: "10.42.0.0/15"
+      - name: verify-vpn
+        image: busybox
+        command:
+        - sh
+        - -c
+        - |
+          sleep 30
+          while ! ping -c 1 8.8.8.8; do
+            echo "Ping failed, retrying in 5"
+            sleep 5
+          done
+          echo "ping succesfull, exiting"
       containers:
       - name: cwa-downloader
         image: {{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}
